spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#Banco local - Brenda Soares
spring.datasource.url= jdbc:postgresql://localhost:5432/assembly
spring.datasource.username=postgres
spring.datasource.password=test123
spring.jpa.hibernate.ddl-auto=update
server.port=8081
